name: darasa_huru
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  url_launcher: ^6.2.5
  share_plus: ^4.5.3
  flutter_html: ^3.0.0
  webview_flutter: ^4.13.0
  html_unescape: ^2.0.0
  flutter_typeahead: ^5.2.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

dependency_overrides:
  flutter_layout_grid: ^2.0.8

